name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up vcpkg
        run: |
          git clone --depth 1 https://github.com/microsoft/vcpkg.git vcpkg
      - name: Build tests
        run: |
          cmake --preset test -DCMAKE_BUILD_TYPE=Debug
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      - name: Run tests
        run: ctest --test-dir ./build
