name: Test

on:
  push:
    branches:
      - main

jobs:
  ctest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up vcpkg
        run: |
          git clone --depth 1 -b 2025.06.13 https://github.com/microsoft/vcpkg.git vcpkg
      - name: Install build tools
        run: |
          sudo apt install ninja-build build-essential
          echo "$(pwd)/vcpkg" >> $GITHUB_PATH
      - name: Build tests
        run: |
          ./vcpkg/bootstrap-vcpkg.sh
          cmake --preset test -DCMAKE_BUILD_TYPE=Debug
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      - name: Run tests
        run: ctest --test-dir ./build
